export type Booth = {
  id: number;
  xOffset: number;
  yOffset: number;
  width?: number;
  height?: number;
  rotation?: number;
  textOverride?: string;
  name?: string;
  imageOverride?: string;
};

export const booths: Booth[] = [
  { id: 1, xOffset: 9, yOffset: 85, name: "Rose Garden" },
  { id: 2, xOffset: 17, yOffset: 85, name: "Daisy Dreams" },
  { id: 3, xOffset: 25, yOffset: 85, name: "Lily Lane" },
  { id: 4, xOffset: 36, yOffset: 85, name: "Tulip Town" },
  { id: 5, xOffset: 44, yOffset: 85, name: "Sunflower Square" },
  { id: 6, xOffset: 52, yOffset: 85, name: "Carnation Corner" },
  { id: 7, xOffset: 62, yOffset: 73, rotation: 45, name: "Orchid Oasis" },
  { id: 8, xOffset: 69.5, yOffset: 67, rotation: 297, name: "Violet Valley" },
  { id: 9, xOffset: 73, yOffset: 60, rotation: 297, name: "Peony Place" },
  { id: 10, xOffset: 73, yOffset: 50, rotation: 297, name: "Hydrangea Haven" },
  {
    id: 11,
    xOffset: 76,
    yOffset: 43,
    rotation: 297,
    name: "Chrysanthemum Court",
  },
  { id: 12, xOffset: 83, yOffset: 38, rotation: 297, name: "Poppy Patch" },
  { id: 13, xOffset: 86, yOffset: 31, rotation: 297, name: "Marigold Market" },
  { id: 14, xOffset: 89, yOffset: 24, rotation: 297, name: "Iris Isle" },
  { id: 15, xOffset: 74, yOffset: 16, rotation: -25, name: "Jasmine Junction" },
  { id: 16, xOffset: 68, yOffset: 19, rotation: -25, name: "Hibiscus Heights" },
  {
    id: 17,
    xOffset: 61,
    yOffset: 26,
    rotation: 90,
    name: "Bluebell Boulevard",
  },
  { id: 18, xOffset: 61, yOffset: 34, rotation: 90, name: "Daffodil Drive" },
  { id: 19, xOffset: 61, yOffset: 42, rotation: 90, name: "Zinnia Zone" },
  { id: 20, xOffset: 59, yOffset: 54, rotation: 90, name: "Geranium Gardens" },
  { id: 21, xOffset: 60, yOffset: 62, rotation: 90, name: "Aster Avenue" },
  {
    id: 22,
    xOffset: 53.5,
    yOffset: 61,
    rotation: 90,
    name: "Snapdragon Street",
  },
  { id: 23, xOffset: 53, yOffset: 53, rotation: 90, name: "Lavender Lane" },
  { id: 24, xOffset: 54, yOffset: 43, rotation: 90, name: "Petunia Plaza" },
  {
    id: 25,
    xOffset: 54.5,
    yOffset: 36,
    width: 5,
    rotation: 90,
    name: "Lemonade stand",
  },
  {
    id: 26,
    xOffset: 54.5,
    yOffset: 29,
    width: 5,
    rotation: 90,
    name: "Lemonade stand",
  },
  {
    id: 27,
    xOffset: 48,
    yOffset: 34,
    rotation: -45,
    name: "Lemonade stand",
  },
  {
    id: 28,
    xOffset: 43,
    yOffset: 39,
    rotation: -45,
    name: "Lemonade stand",
  },
  { id: 29, xOffset: 63, yOffset: 14, rotation: -20, name: "Lemonade stand" },
  { id: 30, xOffset: 57, yOffset: 17, rotation: -25, name: "Lemonade stand" },
  { id: 31, xOffset: 51, yOffset: 22, rotation: -40, name: "Lemonade stand" },
  { id: 32, xOffset: 46, yOffset: 26.5, rotation: -40, name: "Lemonade stand" },
  { id: 33, xOffset: 41, yOffset: 31.5, rotation: -40, name: "Lemonade stand" },
  {
    id: 34,
    xOffset: 39,
    yOffset: 45,
    name: "Lemonade stand",
    rotation: 90,
  },
  {
    id: 35,
    xOffset: 43,
    yOffset: 52,
    rotation: 45,
    name: "Lemonade stand",
  },
  {
    id: 36,
    xOffset: 48,
    yOffset: 58,
    rotation: 45,
    name: "Lemonade stand",
  },
  {
    id: 37,
    xOffset: 38,
    yOffset: 71,
    rotation: -10,
    name: "Lemonade stand",
  },
  {
    id: 38,
    xOffset: 45,
    yOffset: 67,
    rotation: -10,
    name: "Lemonade stand",
  },
  {
    id: 39,
    xOffset: 43,
    yOffset: 61,
    rotation: 45,
    name: "Lemonade stand",
  },
  {
    id: 40,
    xOffset: 38,
    yOffset: 58,
    rotation: 135,
    name: "Lemonade stand",
  },
  {
    id: 41,
    xOffset: 34.5,
    yOffset: 65,
    rotation: 90,
    name: "Lemonade stand",
  },
  {
    id: 42,
    xOffset: 27,
    yOffset: 70,
    rotation: 18,
    name: "Lemonade stand",
  },
  {
    id: 43,
    xOffset: 21,
    yOffset: 68,
    rotation: 18,
    name: "Lemonade stand",
  },
  {
    id: 44,
    xOffset: 22,
    yOffset: 62,
    rotation: 135,
    width: 5,
    name: "Lemonade stand",
  },
  {
    id: 45,
    xOffset: 26,
    yOffset: 57,
    rotation: 135,
    width: 5,
    name: "Lemonade stand",
  },
  {
    id: 46,
    xOffset: 17,
    yOffset: 58,
    rotation: 135,
    width: 5,
    name: "Lemonade stand",
  },
  {
    id: 47,
    xOffset: 22,
    yOffset: 53,
    rotation: 135,
    width: 5,
    name: "Lemonade stand",
  },
  {
    id: 48,
    xOffset: 33,
    yOffset: 53,
    width: 5,
    name: "Lemonade stand",
  },
  {
    id: 49,
    xOffset: 27,
    yOffset: 43,
    rotation: 90,
    width: 4,
    name: "Lemonade stand",
  },
  {
    id: 50,
    xOffset: 33,
    yOffset: 33,
    name: "Lemonade stand",
  },
  {
    id: 51,
    xOffset: 26,
    yOffset: 33,
    rotation: 45,
    name: "Lemonade stand",
  },
  {
    id: 52,
    xOffset: 21.5,
    yOffset: 28,
    rotation: 45,
    name: "Lemonade stand",
  },
  {
    id: 53,
    xOffset: 17,
    yOffset: 23,
    rotation: 45,
    name: "Lemonade stand",
  },
  {
    id: 54,
    xOffset: 12.5,
    yOffset: 18,
    rotation: 45,
    name: "Lemonade stand",
  },
  {
    id: 55,
    xOffset: 8,
    yOffset: 12,
    rotation: 45,
    name: "Lemonade stand",
  },
  {
    id: 56,
    xOffset: 8.5,
    yOffset: 21.5,
    rotation: 45,
    width: 5,
    name: "Lemonade stand",
  },
  {
    id: 57,
    xOffset: 12.5,
    yOffset: 26.5,
    rotation: 45,
    width: 5,
    name: "Lemonade stand",
  },
  {
    id: 58,
    xOffset: 17,
    yOffset: 32,
    rotation: 45,
    width: 5,
    name: "Lemonade stand",
  },
  {
    id: 59,
    xOffset: 22,
    yOffset: 37,
    rotation: 45,
    width: 5,
    name: "Lemonade stand",
  },
  {
    id: 60,
    xOffset: 8.5,
    yOffset: 30,
    rotation: 90,
    width: 5,
    name: "Lemonade stand",
  },
  {
    id: 61,
    xOffset: 8.5,
    yOffset: 36.5,
    rotation: 90,
    width: 5,
    name: "Lemonade stand",
  },
  {
    id: 62,
    xOffset: 9,
    yOffset: 43,
    rotation: 90,
    width: 5,
    name: "Lemonade stand",
  },
  {
    id: 63,
    xOffset: 10,
    yOffset: 49,
    rotation: 85,
    width: 5,
    name: "Lemonade stand",
  },
  {
    id: 64,
    xOffset: 11,
    yOffset: 56,
    rotation: 80,
    width: 5,
    name: "Lemonade stand",
  },
  {
    id: 65,
    xOffset: 8,
    yOffset: 65,
    rotation: 50,
    name: "Lemonade stand",
  },
  {
    id: 66,
    xOffset: 15,
    yOffset: 8,
    name: "Lemonade stand",
  },
  {
    id: 67,
    xOffset: 22,
    yOffset: 8,
    name: "Lemonade stand",
  },
  {
    id: 68,
    xOffset: 30,
    yOffset: 9,
    name: "Lemonade stand",
  },
  {
    id: 69,
    xOffset: 37,
    yOffset: 9,
    name: "Lemonade stand",
  },
  {
    id: 70,
    xOffset: 44,
    yOffset: 9,
    name: "Lemonade stand",
  },
  {
    id: 71,
    xOffset: 52,
    yOffset: 10,
    name: "Lemonade stand",
  },
  {
    id: 72,
    xOffset: 59,
    yOffset: 10,
    name: "Lemonade stand",
  },
  {
    id: 73,
    xOffset: 66,
    yOffset: 10,
    name: "Lemonade stand",
  },
  {
    id: 74,
    xOffset: 2,
    yOffset: 50,
    rotation: 90,
    name: "Lemonade stand",
  },
  {
    id: 75,
    xOffset: 2,
    yOffset: 30,
    rotation: 90,
    name: "Lemonade stand",
  },
];
