export type Booth = {
  id: number;
  xOffset: number;
  yOffset: number;
  width?: number;
  height?: number;
  rotation?: number;
  textOverride?: string;
  name?: string;
  imageOverride?: string;
};

export const booths: Booth[] = [
  { id: 1, xOffset: 9, yOffset: 85, name: "Stained Glass Mosaic" },
  { id: 2, xOffset: 17, yOffset: 85, name: "Wyattville Garden Center" },
  { id: 3, xOffset: 25, yOffset: 85, name: "Wyattville Garden Center" },
  { id: 4, xOffset: 36, yOffset: 85, name: "" },
  { id: 5, xOffset: 44, yOffset: 85, name: "Anderson Greenhouses" },
  { id: 6, xOffset: 52, yOffset: 85, name: "Anderson Greenhouses" },
  {
    id: 7,
    xOffset: 62,
    yOffset: 73,
    rotation: 45,
    name: "Alex Stoll Stainless Steel Art",
  },
  {
    id: 8,
    xOffset: 69.5,
    yOffset: 67,
    rotation: 297,
    name: "Stanish Family Garden",
  },
  {
    id: 9,
    xOffset: 73,
    yOffset: 60,
    rotation: 297,
    name: "Green Mountain Energy",
  },
  { id: 10, xOffset: 73, yOffset: 50, rotation: 297, name: "" },
  {
    id: 11,
    xOffset: 76,
    yOffset: 43,
    rotation: 297,
    name: "",
  },
  { id: 12, xOffset: 83, yOffset: 38, rotation: 297, name: "Ariel's Attic" },
  { id: 13, xOffset: 86, yOffset: 31, rotation: 297, name: "Ariel's Attic" },
  { id: 14, xOffset: 89, yOffset: 24, rotation: 297, name: "" },
  {
    id: 15,
    xOffset: 74,
    yOffset: 16,
    rotation: -25,
    name: "Park Avenue Greenhouse",
  },
  { id: 16, xOffset: 68, yOffset: 19, rotation: -25, name: "Saylor's Farm" },
  {
    id: 17,
    xOffset: 61,
    yOffset: 26,
    rotation: 90,
    name: "Moonrise Porcelain",
  },
  { id: 18, xOffset: 61, yOffset: 34, rotation: 90, name: "" },
  {
    id: 19,
    xOffset: 61,
    yOffset: 42,
    rotation: 90,
    name: "Chocolate Moonshine",
  },
  { id: 20, xOffset: 59, yOffset: 54, rotation: 90, name: "Wet Dog Studio" },
  { id: 21, xOffset: 60, yOffset: 62, rotation: 90, name: "" },
  {
    id: 22,
    xOffset: 53.5,
    yOffset: 61,
    rotation: 90,
    name: "Vase Place",
  },
  { id: 23, xOffset: 53, yOffset: 53, rotation: 90, name: "Cindy's Munchies" },
  { id: 24, xOffset: 54, yOffset: 43, rotation: 90, name: "" },
  {
    id: 25,
    xOffset: 54.5,
    yOffset: 36,
    width: 5,
    rotation: 90,
    name: "Jento Soaps",
  },
  {
    id: 26,
    xOffset: 54.5,
    yOffset: 29,
    width: 5,
    rotation: 90,
    name: "Country Fancies",
  },
  {
    id: 27,
    xOffset: 48,
    yOffset: 34,
    rotation: -45,
    name: "Pampas Creek",
  },
  {
    id: 28,
    xOffset: 43,
    yOffset: 39,
    rotation: -45,
    name: "Pampas Creek",
  },
  { id: 29, xOffset: 63, yOffset: 14, rotation: -20, name: "Lamb's Ear" },
  { id: 30, xOffset: 57, yOffset: 17, rotation: -25, name: "Greenhouse 22" },
  { id: 31, xOffset: 51, yOffset: 22, rotation: -40, name: "Joey Crafts" },
  { id: 32, xOffset: 46, yOffset: 26.5, rotation: -40, name: "Joker's Wild" },
  {
    id: 33,
    xOffset: 41,
    yOffset: 31.5,
    rotation: -40,
    name: "Fairlamb Lavendar",
  },
  {
    id: 34,
    xOffset: 39,
    yOffset: 45,
    name: "Children's Tent",
    rotation: 90,
  },
  {
    id: 35,
    xOffset: 43,
    yOffset: 52,
    rotation: 45,
    name: "Carriage House Creation",
  },
  {
    id: 36,
    xOffset: 48,
    yOffset: 58,
    rotation: 45,
    name: "",
  },
  {
    id: 37,
    xOffset: 38,
    yOffset: 71,
    rotation: -10,
    name: "Sunny Sprout",
  },
  {
    id: 38,
    xOffset: 45,
    yOffset: 67,
    rotation: -10,
    name: "Glass Gal",
  },
  {
    id: 39,
    xOffset: 43,
    yOffset: 61,
    rotation: 45,
    name: "Green Thumb Chef",
  },
  {
    id: 40,
    xOffset: 38,
    yOffset: 58,
    rotation: 135,
    name: "Al's Fountains",
  },
  {
    id: 41,
    xOffset: 34.5,
    yOffset: 65,
    rotation: 90,
    name: "Al's Fountains",
  },
  {
    id: 42,
    xOffset: 27,
    yOffset: 70,
    rotation: 18,
    name: "Twig Tree Nursery",
  },
  {
    id: 43,
    xOffset: 21,
    yOffset: 68,
    rotation: 18,
    name: "Nature Arts and Crafts",
  },
  {
    id: 44,
    xOffset: 22,
    yOffset: 62,
    rotation: 135,
    width: 5,
    name: "Longabarger Baskets (Sat), Brown Stone Studio (Sun)",
  },
  {
    id: 45,
    xOffset: 26,
    yOffset: 57,
    rotation: 135,
    width: 5,
    name: "",
  },
  {
    id: 46,
    xOffset: 17,
    yOffset: 58,
    rotation: 135,
    width: 5,
    name: "Traveling Greenhouse",
  },
  {
    id: 47,
    xOffset: 22,
    yOffset: 53,
    rotation: 135,
    width: 5,
    name: "",
  },
  {
    id: 48,
    xOffset: 33,
    yOffset: 53,
    width: 5,
    name: "Musician Tent",
  },
  {
    id: 49,
    xOffset: 27,
    yOffset: 43,
    rotation: 90,
    width: 4,
    name: "FGA Tent",
  },
  {
    id: 50,
    xOffset: 33,
    yOffset: 33,
    name: "",
  },
  {
    id: 51,
    xOffset: 26,
    yOffset: 33,
    rotation: 45,
    name: "DJ's Greenhouse",
  },
  {
    id: 52,
    xOffset: 21.5,
    yOffset: 28,
    rotation: 45,
    name: "",
  },
  {
    id: 53,
    xOffset: 17,
    yOffset: 23,
    rotation: 45,
    name: "Penn State Master Gardeners",
  },
  {
    id: 54,
    xOffset: 12.5,
    yOffset: 18,
    rotation: 45,
    name: "Humble Habitats",
  },
  {
    id: 55,
    xOffset: 8,
    yOffset: 12,
    rotation: 45,
    name: "",
  },
  {
    id: 56,
    xOffset: 8.5,
    yOffset: 21.5,
    rotation: 45,
    width: 5,
    name: "Shade Tree Commission",
  },
  {
    id: 57,
    xOffset: 12.5,
    yOffset: 26.5,
    rotation: 45,
    width: 5,
    name: "Knots and Folds",
  },
  {
    id: 58,
    xOffset: 17,
    yOffset: 32,
    rotation: 45,
    width: 5,
    name: "Pastries by Andrea",
  },
  {
    id: 59,
    xOffset: 22,
    yOffset: 37,
    rotation: 45,
    width: 5,
    name: "Calico Creationz",
  },
  {
    id: 60,
    xOffset: 8.5,
    yOffset: 30,
    rotation: 90,
    width: 5,
    name: "Deets SugarHouse",
  },
  {
    id: 61,
    xOffset: 8.5,
    yOffset: 36.5,
    rotation: 90,
    width: 5,
    name: "Deets SugarHouse",
  },
  {
    id: 62,
    xOffset: 9,
    yOffset: 43,
    rotation: 90,
    width: 5,
    name: "",
  },
  {
    id: 63,
    xOffset: 10,
    yOffset: 49,
    rotation: 85,
    width: 5,
    name: "Tickle My Ribs",
  },
  {
    id: 64,
    xOffset: 11,
    yOffset: 56,
    rotation: 80,
    width: 5,
    name: "Tickle My Ribs",
  },
  {
    id: 65,
    xOffset: 8,
    yOffset: 65,
    rotation: 50,
    name: "Cowboy Kettle Korn",
  },
  {
    id: 66,
    xOffset: 15,
    yOffset: 8,
    name: "",
  },
  {
    id: 67,
    xOffset: 22,
    yOffset: 8,
    name: "Whitneys Crafts and Jewelry",
  },
  {
    id: 68,
    xOffset: 30,
    yOffset: 9,
    name: "Barbers Orchard",
  },
  {
    id: 69,
    xOffset: 37,
    yOffset: 9,
    name: "Barbers Orchard",
  },
  {
    id: 70,
    xOffset: 44,
    yOffset: 9,
    name: "Barbers Orchard",
  },
  {
    id: 71,
    xOffset: 52,
    yOffset: 10,
    name: "Lamb's Ear",
  },
  {
    id: 72,
    xOffset: 59,
    yOffset: 10,
    name: "",
  },
  {
    id: 73,
    xOffset: 66,
    yOffset: 10,
    name: "Artistic Home Selections",
  },
  {
    id: 74,
    xOffset: 2,
    yOffset: 50,
    rotation: 90,
    name: "",
  },
  {
    id: 75,
    xOffset: 2,
    yOffset: 30,
    rotation: 90,
    name: "",
  },
];
